version: '3'

services:
  nginx:
    ports:
      - 3000:80

  my-node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.dev
    command: npm run dev

  mongo:
    env_file:
      - ./.env.dev