version: '3'

services:
  my-node-app:
    container_name: my-node-app
    build: .
    image: brunoedsr/node-exp-test
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env